version: '2'
services:
  web:
    build: 
      context: .
      dockerfile: "../../base/django/5.2/DockerFile"
    ports:
    - "8085:8000"
    depends_on:
    - db
    volumes:
    - ./src:/usr/src
    - ./docker-entrypoint.sh:/docker-entrypoint.sh
    entrypoint:
    - bash
    - /docker-entrypoint.sh
    command:
    - python
    - /usr/src/manage.py
    - runserver
    - 0.0.0.0:8000
      
  db:
    image: "m.daocloud.io/docker.io/library/postgres:latest"
    environment:
    - POSTGRES_PASSWORD=postgres
    - POSTGRES_DB=CVE-2025-57833
