version: '3'
services:
 web:
   image: vulhub/imagemagick:7.0.8-27-php
   command: php -t /var/www/html -S 0.0.0.0:8080
   volumes:
    - ./index.php:/var/www/html/index.php
   ports:
    - "8080:8080"