version: '2.4'
services:
  core:
    image: vulhub/jumpserver:3.6.4
    ulimits:
      core: 0
    restart: always
    tty: true
    environment:
      MAGNUS_PORT: ${MAGNUS_PORT:-30000-30020}
    env_file: config.env
    ports:
      - "8080:80"

  mysql:
    image: mariadb:10.11.5
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    env_file: config.env

  redis:
    image: redis:6.2.13
    command: redis-server --requirepass $REDIS_PASSWORD --loglevel warning --maxmemory-policy allkeys-lru
    env_file: config.env
