version: '2'
services:
 weblogic:
   image: vulhub/weblogic:10.3.6.0-2017
   volumes:
    - ./web:/root/Oracle/Middleware/user_projects/domains/base_domain/autodeploy
   ports:
    - "7001:7001"
    - "5556:5556"