version: "2"

services:
  jira:
    image: vulhub/jira:8.1.0
    ports:
      - "8080:8080"
    links:
      - smtpd

  smtpd:
    build:
      context: .
      dockerfile: Dockerfile.smtpd
