#
# PRODUCTION
#
production:
  adapter: {{DB_ADAPTER}}
  encoding: {{DB_ENCODING}}
  collation: utf8_general_ci
  reconnect: false
  database: {{DB_NAME}}
  host: {{DB_HOST}}
  port: {{DB_PORT}}
  username: {{DB_USER}}
  password: "{{DB_PASS}}"
  pool: {{DB_POOL}}

