services:
 nginx:
   image: vulhub/nginx:1.4.2
   volumes:
    - ./nginx.conf:/usr/local/nginx/conf/nginx.conf
    - ./www:/usr/local/nginx/html
   ports:
    - "8080:80"
 php:
   build: ./php-fpm/
   volumes:
    - ./www:/var/www/html