services:
 server:
   image: vulhub/zabbix:3.0.3-server
   command: server
   depends_on:
    - mysql
   environment: 
    - DATABASE_HOST=mysql
    - DATABASE_PORT=3306
    - DATABASE_USER=root
    - DATABASE_PASS=root
    - DATABASE_NAME=zabbix
 agent:
   image: vulhub/zabbix:3.0.3-server
   command: agent
   depends_on:
    - mysql
    - server
   environment: 
    - ZBX_SRV_HOST=server
    - ZBX_SRV_HOST_ACT=server
    - DATABASE_HOST=mysql
    - DATABASE_PORT=3306
    - DATABASE_USER=root
    - DATABASE_PASS=root
    - DATABASE_NAME=zabbix
 mysql:
   image: mysql:5
   environment: 
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=zabbix
   volumes:
    - ./database/:/docker-entrypoint-initdb.d/
 web:
   image: vulhub/zabbix:3.0.3-web
   depends_on:
    - server
    - mysql
   environment:
    - DATABASE_HOST=mysql
    - DATABASE_PORT=3306
    - DATABASE_USER=root
    - DATABASE_PASS=root
    - DATABASE_NAME=zabbix
    - ZBX_SRV_HOST=server
    - ZBX_SRV_PORT=10051
   ports:
    - "8080:80"