version: "3.7"

services:

  hertzbeat:
    image: vulhub/hertzbeat:1.4.4
    container_name: hertzbeat
    environment:
      TZ: Asia/Shanghai
      LANG: zh_CN.UTF-8
    ports:
      - "1157:1157"
      - "1158:1158"
