services:
  apisix:
    image: vulhub/apisix:2.9
    volumes:
      - ./apisix.yml:/usr/local/apisix/conf/config.yaml
    depends_on:
      - etcd
    ports:
      - "9080:9080"
      - "9091:9091"
      - "9443:9443"
  dashboard:
    image: vulhub/apisix-dashboard:2.9.0
    volumes:
      - ./dashboard.yml:/usr/local/apisix-dashboard/conf/conf.yaml
    depends_on:
      - etcd
    ports:
      - "9000:9000"
  etcd:
    image: gcr.io/etcd-development/etcd:v3.4.15
    command:
      - /usr/local/bin/etcd
      - --listen-client-urls=http://0.0.0.0:2379
      - --advertise-client-urls=http://0.0.0.0:2379
    ports:
      - "2379:2379/tcp"
