name: Vulhub Docker Image CI

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:

  images-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: active-mq
      run: |
        bash tests/images-build.sh base/activemq/5.11.1 base/activemq/5.11.1/with-cron base/activemq/5.13.2
    - name: apereo-cas
      run: |
        bash tests/images-build.sh base/apereo-cas/4.1.5
    - name: appweb
      run: |
        bash tests/images-build.sh base/appweb/7.0.1
    - name: aria2
      run: |
        bash tests/images-build.sh base/aria2/1.18.8
    - name: baselinux
      run: |
        bash tests/images-build.sh base/baselinux/centos-6
    - name: bash
      run: |
        bash tests/image-build.sh base/bash/4.3.0 "vulhub/bash:4.3.0"
        bash tests/images-build.sh base/bash/4.3.0/with-httpd